# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.3

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      - run:
          command: npm install --force
          name: Install Dependencies
      - run:
          command: npm run build
          name: Build app
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run upload:coverage
          name: Upload coverage report

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  run_tests: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.

    jobs:
      - build_and_test
